### ISSUE TITLE
Wineprefix not created error

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#52] opened 2024-04-03 18:15 UTC
When I get to the configure wine options during setup (install dxvk etc) i get this error:

Writing image to "/media/ade/Temp/Temp/build/Age-Of-Empires/icon/icon.png"
I :: Writing grayscale image to "/media/ade/Temp/Temp/build/Age-Of-Empires/icon/icon.grayscale.png"
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/Age-Of-Empires/gameimage.json"' as UPDATE
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: application: Age-Of-Empires
I :: image: "/media/ade/Temp/Temp/build/wine.flatimage"
I :: prefix: "/media/ade/Temp/Temp/build/Age-Of-Empires/wine"
I :: [e] :: bwrap: Can't create file at /tmp/fim/instance/502568f_20240217183447/mount/KIdoON.mount.dwarfs.usr//lib/libnvidia-gtk2.so.510.47.03: Function not implemented
I :: [e] :: Killed
I :: Finished Command: '/media/ade/Temp/Temp/build/wine.flatimage fim-exec wine.sh regedit'
Wine prefix does not exist

**Comment by ruanformigoni** [comment] 2024-04-03 19:23
Thanks for the report @Blad3forc3 ! I found the issue and fixed it, it was on the [wine runner](https://github.com/gameimage/runners) when used with nvidia, erase the build folder and re-download the wine packages. That should do it :smile:

**Comment by ruanformigoni** [comment] 2024-04-03 20:26
Fixed in latest wine runner, thanks! The issue is that the HOME was set `I :: [o] :: [wine.sh] HOME : /home/ade`, and it was building from an external drive.

**Comment by ruanformigoni** [comment] 2024-04-03 20:50
Just resolved other issues with winetricks, please wait for this [pipeline](https://github.com/gameimage/runners/actions/runs/8545297050) to finish.

**Comment by ruanformigoni** [comment] 2024-04-04 14:49
I'll assume this is fixed, feel free to re-open if it is not. :smile:

**Closed by ruanformigoni** 2024-04-04 14:49 UTC

**Comment by Blad3forc3** [comment] 2024-04-04 14:54
This was fixed yes :)
