### ISSUE TITLE
Version v1.5.0 does not work correctly on the steam deck.

### ISSUE THREAD

**Issue by malaespera** [ruanformigoni/gameimage#131] opened 2024-11-19 22:12 UTC
Version v1.5.0 does not work correctly for me on the steam deck. Does not create the wine folder

gameimage.rs:58: I :: [o]: bwrap: Can't make overlay mount on /newroot/ with options upperdir=/oldroot/home/deck/Downloads/gameimage/build/cache/.linux.flatimage.config/overlays/upperdir,workdir=/oldroot/home/deck/Downloads/gameimage/build/cache/.linux.flatimage.config/overlays/workdir,lowerdir=/oldroot/tmp/fim/app/df01343_20241116151300/instance/OfEEBc/mount/layers/2:/oldroot/tmp/fim/app/df01343_20241116151300/instance/OfEEBc/mount/layers/1:/oldroot/tmp/fim/app/df01343_20241116151300/instance/OfEEBc/mount/layers/0,userxattr: Invalid argument

**Comment by ruanformigoni** [comment] 2024-11-20 02:44
Thank you for reporting this issue @malaespera . You can use `FIM_FUSE_OVERLAYFS=1 ./my-game.flatimage` as a workaround while I investigate the cause of this issue.

**Comment by malaespera** [comment] 2024-11-20 10:34
It is possible to continue using version v1.4.2 in the meantime?

**Comment by ruanformigoni** [comment] 2024-11-23 00:28
Hi @malaespera , sure. I've re-enabled it.

**Comment by ruanformigoni** [comment] 2024-12-16 20:52
This should be fixed in `v1.6.0`.

**Closed** 2024-12-17 23:26 UTC
