### ISSUE TITLE
Error in latest GameImage, doesnt happen in earlier GameImage

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#22] opened 2023-03-18 13:16 UTC
Hi,

I tried a game with the latest appimage (with the latest wine staging version 8.3) and the game complains about not finding a file within the games installation directory. I have tried the same game with an earlier version of GameImage (0.4) with the same Wine Staging version (8.3) and it plays fine. Has there been a change as regards directory structure and where the game can find its required files?

**Comment by Blad3forc3** [comment] 2023-03-18 15:39
It's a file within the actual game installation, a fonts file, which is there.
The directory structure is in the root dir of the game installation is a DATA folder and a GAME folder. The exe is run from inside the GAME folder and complains about a missing file inside the DATA folder. This started happening during the change to the unionfs structure as using gameimage 0.4 it works. I am not sure which exact gameimage it broke on as i dont have access to the earlier versions as you sent me the gameimage version 0.4.
Also i have a few games that NEED to be run by a launcher and invoking different exes within the game dir. They cannot be run individually and complain about needing to run from the launcher exe. Using gameimage these fail because the launcher runs but when selecting an episode (a separate exe) from the launcher the gameimage just fails to invoke the new exe for the episode

**Comment by ruanformigoni** [comment] 2023-04-01 19:32
Closing this as a duplicate of #23 , since both cases seem to be related to wine.

**Closed by ruanformigoni** 2023-04-01 19:32 UTC
